#!/bin/bash

which swift > /dev/null 2>&1 || (echo "Xcode Command Line Tools is not installed, unable to perform conversion."; exit 1)

./printIssues.swift
./convert_ios.swift
./convert_android.swift

